version: '3.8'

services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: quiz-wireguard
    restart: unless-stopped
    ports:
      - "51820:51820/udp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      - quiz-network
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
      - SERVERURL=auto  # Détection automatique IP publique
      - SERVERPORT=51820
      - PEERS=5  # Nombre de clients (téléphones, PC, etc.)
      - PEERDNS=1.1.1.1,8.8.8.8
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=10.13.13.0/24,172.20.0.0/16
    volumes:
      - ./wireguard-config:/config
      - /lib/modules:/lib/modules

networks:
  quiz-network:
    external: true