
version: '3.8'

services:
  # Base de données PostgreSQL pour développement
  postgres-dev:
    image: postgres:15-alpine
    container_name: quiz-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: quiz_app_dev
      POSTGRES_USER: quiz_user
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    ports:
      - "5433:5432"
    networks:
      - quiz-dev-network

  # Backend en mode développement
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: quiz-api-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgresql://quiz_user:dev_password@postgres-dev:5432/quiz_app_dev
      CORS_ORIGIN: http://localhost:3000
    volumes:
      - ./backend/src:/app/src
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    ports:
      - "3001:3001"
    depends_on:
      - postgres-dev
    networks:
      - quiz-dev-network
    command: npm run dev

networks:
  quiz-dev-network:
    driver: bridge

volumes:
  postgres_dev_data:
    driver: local
