
version: '3.8'

services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: quiz-wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
      - SERVERURL=auto  # Détection automatique IP publique
      - SERVERPORT=51820
      - PEERS=5  # Nombre de clients (téléphones, PC, etc.)
      - PEERDNS=1.1.1.1,8.8.8.8
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0,192.168.1.0/24
    volumes:
      - ./wireguard-config:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - quiz-network

networks:
  quiz-network:
    external: true
